Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketLine.Data;
using TicketLine.Models;

namespace TicketLine.Controllers
{
    public class FlightsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public FlightsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<string> GetCurrentUserId()
        {
            ApplicationUser usr = await GetCurrentUserAsync();
            return usr?.Id;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Flights
        public async Task<IActionResult> Index(string searchString)
        {
            var flights = from f in _context.Flight
                          select f;

            var applicationDbContext = _context.Flight.Include(f => f.Boarding).Include(f => f.Destination);

            if(!String.IsNullOrEmpty(searchString))
            {
                flights = flights.Where(f => f.Boarding.City.Contains(searchString) || f.Destination.City.Contains(searchString)
                                          || f.Boarding.Name.Contains(searchString) || f.Destination.Name.Contains(searchString)).
                                          Include(f => f.Boarding).Include(f => f.Destination);

                return View(await flights.ToListAsync());
            }

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flight
                .Include(f => f.Boarding)
                .Include(f => f.Destination)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // GET: Flights/Create
        public IActionResult Create()
        {
            ViewData["BoardingId"] = new SelectList(_context.Airport, "Id", "City");
            ViewData["DestinationId"] = new SelectList(_context.Airport, "Id", "City");
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BoardingId,DestinationId,TakeoffTime,ArrivalTime")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                _context.Add(flight);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoardingId"] = new SelectList(_context.Airport, "Id", "City", flight.BoardingId);
            ViewData["DestinationId"] = new SelectList(_context.Airport, "Id", "City", flight.DestinationId);
            return View(flight);
        }

        // GET: Flights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flight.FindAsync(id);
            if (flight == null)
            {
                return NotFound();
            }
            ViewData["BoardingId"] = new SelectList(_context.Airport, "Id", "City", flight.BoardingId);
            ViewData["DestinationId"] = new SelectList(_context.Airport, "Id", "City", flight.DestinationId);
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BoardingId,DestinationId,TakeoffTime,ArrivalTime")] Flight flight)
        {
            if (id != flight.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoardingId"] = new SelectList(_context.Airport, "Id", "City", flight.BoardingId);
            ViewData["DestinationId"] = new SelectList(_context.Airport, "Id", "City", flight.DestinationId);
            return View(flight);
        }

        // GET: Flights/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flight
                .Include(f => f.Boarding)
                .Include(f => f.Destination)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flight = await _context.Flight.FindAsync(id);
            _context.Flight.Remove(flight);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        // POST : Flights/CreateTicket/5
        public async Task<IActionResult> CreateTicket(int id)
        {
            var flight = await _context.Flight.FindAsync(id);
            var airplane = _context.Airplane.Where(p => p.FlightId == id);
            var seat = _context.Seat.Include(f => f.Ticket).Where(p => p.AirplaneId == airplane.FirstOrDefault().Id && p.Ticket == null);

            if(seat == null)
            {
                ModelState.AddModelError(string.Empty, "No more seats are left for this flight.");
                return RedirectToAction(nameof(Index));
            }

            var ticket = new Ticket
            {
                SeatId = seat.FirstOrDefault().Id,
                OwnerId = await GetCurrentUserId()
            };

            if (ticket != null)
            {
                _context.Ticket.Add(ticket);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Your request could not be processed!");
                return RedirectToAction(nameof(Index));
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        private bool FlightExists(int id)
        {
            return _context.Flight.Any(e => e.Id == id);
        }
    }
}

Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketLine.Data;
using TicketLine.Models;

namespace TicketLine.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public TicketsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<string> GetCurrentUserId()
        {
            ApplicationUser usr = await GetCurrentUserAsync();
            return usr?.Id;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Tickets
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var id_user = await GetCurrentUserId();
            var applicationDbContext = id_user != null ? _context.Ticket.Where(f => f.OwnerId == id_user).Include(t => t.Seat).ThenInclude(t => t.Airplane).ThenInclude(t => t.Flight).ThenInclude(t => t.Boarding)
                                                      .Include(t => t.Seat).ThenInclude(t => t.Airplane).ThenInclude(t => t.Flight).ThenInclude(t => t.Destination) :
                                                      _context.Ticket.Include(t => t.Seat).ThenInclude(t => t.Airplane).ThenInclude(t => t.Flight).ThenInclude(t => t.Boarding)
                                                      .Include(t => t.Seat).ThenInclude(t => t.Airplane).ThenInclude(t => t.Flight).ThenInclude(t => t.Destination);

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket.Include(t => t.Seat).ThenInclude(t => t.Airplane).ThenInclude(t => t.Flight).ThenInclude(t => t.Boarding)
                                              .Include(t => t.Seat).ThenInclude(t => t.Airplane).ThenInclude(t => t.Flight).ThenInclude(t => t.Destination)
                                              .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public IActionResult Create()
        {
            ViewData["SeatId"] = new SelectList(_context.Seat, "Id", "Id");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,SeatId")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SeatId"] = new SelectList(_context.Seat, "Id", "Id", ticket.SeatId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["SeatId"] = new SelectList(_context.Seat, "Id", "Id", ticket.SeatId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,SeatId")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SeatId"] = new SelectList(_context.Seat, "Id", "Id", ticket.SeatId);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Seat)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Ticket.FindAsync(id);
            _context.Ticket.Remove(ticket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Ticket.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_DisplayFlightsPartial.cshtml
@model Flight
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

@{ 
    var pathIndex = "../img/" + Model.Destination.City + ".jpg";
    var pathDetails = "/img/" + Model.Destination.City + ".jpg";
    var showButtons = (bool) ViewData["ShowButtons"];
    var seatNumber = (int?)ViewData["ShowSeat"];
}

<div class="col-4">
    <div class="card">
        @if (showButtons)
        { 
            <img class="card-img-top" src="@pathIndex" />
        }
        else { 
            <img class="card-img-top" src="@pathDetails" />
        }
    <div class="card-body">
        <h4 class="card-title">@Model.Boarding.City to @Model.Destination.City</h4>
        <p class="card-text">Boarding airport: @Model.Boarding.Name</p>
        <p class="card-text">Destination airport: @Model.Destination.Name</p>
        <p class="card-text">Takeoff time: @Model.TakeoffTime</p>
        <p class="card-text">Arrival time: @Model.ArrivalTime</p>
        @if (seatNumber != null)
        {
            <p class="card-text">Seat number: @seatNumber</p>
        }
        @if (showButtons)
        {
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
            }
            <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@Model.Id">Details</a>
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                <a class="btn btn-outline-primary" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
            }
        }
    </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Server
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TicketLine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-flatly.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img class="app-icon" src="~/icons/paper-plane.svg" width="30" height="30"/>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TicketLine</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flights" asp-action="Index">Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Airports" asp-action="Index">Airports</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Airplanes" asp-action="Index">Airplanes</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TicketLine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>